# Generated by Django 6.0.5 on 2026-06-02 15:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tecnologia',
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('disciplina', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('pausado', 'Pausado')], max_length=20)),
                ('repositorio', models.URLField(blank=True, null=True)),
                ('integrantes', models.TextField(help_text='Informe os nomes dos integrantes separados por vírgula.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
                ('tecnologias', models.ManyToManyField(related_name='projetos', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
