# Generated by Django 6.0.5 on 2026-06-03 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
